config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#index'
  resources :cars
  resources :parkings
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    belongs_to :user
    has_many :parkings, dependent: :destroy
end

app/models/parking.rb
class Parking < ApplicationRecord
    belongs_to :car
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :parkings, dependent: :destroy
  has_many :cars, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :phone, :username, :email, :password, :current_password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :phone, :username, :email, :password, :current_password)}
          end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @user = current_user
    end

    def create
        Car.create(car_params)

        redirect_to :controller => 'cars', :action => 'index' 
    end

    def new
        @car = Car.new
    end

    def edit
        @car = Car.find(params[:id])
    end

    def show
        @car = Car.find(params[:id])
    end

    def update
        @car = Car.find(params[:id])
        @car.update(course_params)

        redirect_to :controller => 'cars', :action => 'show' 
    end

    def destroy
        @car = Car.find(params[:id])
        @car.destroy
    end

    private
    def car_params
        params.require(:car).permit(:nickname,:description, :default)
    end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @user = current_user
    end

    def show
        @parking = Parking.find(params[:id])
        @parkedCar = @parking.car
    end

    def new
        @parking = Parking.new
    end

    def create
        @parking = Parking.new(parking_params)
        if @parking.save
            redirect_to :controller => 'parkings', :action => 'index', alert: "Parking session successfully created!"
        else
            redirect_to new_parking_path, alert: "Error creating parking."
        end 
    end

    def edit
        @parking = Parking.find(params[:id])
    end

    def update
        @parking = Parking.find(params[:id])
        @parking.update(parking_params)

        redirect_to :controller => 'cars', :action => 'show' 
    end

    def destroy
        @parking = Parking.find(params[:id])
        @parking.destroy
    end

    private
    def parking_params
        params.require(:parking).permit(:active, :address, :start_latitude, :end_latitude,:start_longitude, :end_longitude, :move_by, :remind_at, :user_id,:car_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!

    def index
      @user = current_user
      @parking = Parking.all

    end

    def show
        @user = User.find(params[:id])
        # method: get
        # action: index
        # template: users/show.html.erb
    end

    def new
        @user = User.new
    # method: get
    # action: index
    # template: users/new.html.erb
    end

    def create
        @user = User.new(user_params)

        if @user.save
            redirect_to @user
        else
            render 'new'
        end
    end

    def edit
        @user = current_user
        # template: users/edit.html.erb
    end
    
    def update
        @user = current_user
    
        if @user.update(user_params)
            redirect_to @user
        else
            render 'edit'
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
    end

    private

        def user_params
            params.require(:user).permit(:first_name, :last_name, :phone, :email, :password)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/index.html.erb
<% @user.cars.each do |car| %>
    <h1> <%= car.nickname %> </h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parkner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/parkings/create.html.erb
<%= form_for @parking do |p| %>
    <label for="active"> Active? </label>
    <%= p.check_box :active %> <br>

    <label for="address"> Address: </label>
    <%= p.text_field :address %> <br>

    <label for="start_latitude"> Start Latitude: </label>
    <%= p.text_field :start_latitude %> <br>

    <label for="end_latitude"> End Latitude: </label>
    <%= p.text_field :end_latitude %> <br>

    <label for="start_longitude"> Start Longitude: </label>
    <%= p.text_field :start_longitude %> <br>

    <label for="end_longitude"> End Longitude: </label>
    <%= p.text_field :end_longitude %> <br>

    <label for="move_by"> Move By: </label>
    <%= p.datetime_field :move_by %> <br>

    <label for="remind_at"> Remind At: </label>
    <%= p.datetime_field :remind_at %> <br>

    <label for="remind_at"> Remind At: </label>
    <%= p.datetime_field :remind_at %> <br>

    <%= p.hidden_field :user_id, :value=>current_user.id %>
    <label for="car"> Car: </label>
    <%= p.select :car_id, Car.all.map{|x| [x.nickname, x.id]} %>
    <%= p.submit %>
<% end %>

app/views/parkings/edit.html.erb
<%= form_for @parking do |p| %>
    <label for="active"> Active? </label>
    <%= p.check_box :active %> <br>

    <label for="address"> Address: </label>
    <%= p.text_field :address %> <br>

    <label for="start_latitude"> Start Latitude: </label>
    <%= p.text_field :start_latitude %> <br>

    <label for="end_latitude"> End Latitude: </label>
    <%= p.text_field :end_latitude %> <br>

    <label for="start_longitude"> Start Longitude: </label>
    <%= p.text_field :start_longitude %> <br>

    <label for="end_longitude"> End Longitude: </label>
    <%= p.text_field :end_longitude %> <br>

    <label for="move_by"> Move By: </label>
    <%= p.datetime_field :move_by %> <br>

    <label for="remind_at"> Remind At: </label>
    <%= p.datetime_field :remind_at %> <br>

    <label for="remind_at"> Remind At: </label>
    <%= p.datetime_field :remind_at %> <br>

    <%= p.hidden_field :user_id, :value=>current_user.id %>
    <label for="car"> Car: </label>
    <%= p.select :car_id, Car.all.map{|x| [x.nickname, x.id]} %>
    <%= p.submit %>
<% end %>

app/views/parkings/index.html.erb
<% @user.parkings.each do |session| %>
    <% @car = Car.find(session.car_id) %>
     <h2> <a href="/parkings/<%= session.id %>"> <%= @car.nickname %> - <%= session.created_at.to_date.strftime("%B %d, %Y") %> Session </a></h2>
 <% end %>

 <a href="/parkings/new"> Add Session </a>

app/views/parkings/new.html.erb
<%= form_for @parking do |p| %>
    <label for="active"> Active? </label>
    <%= p.check_box :active %> <br>

    <label for="address"> Address: </label>
    <%= p.text_field :address %> <br>

    <label for="start_latitude"> Start Latitude: </label>
    <%= p.text_field :start_latitude %> <br>

    <label for="end_latitude"> End Latitude: </label>
    <%= p.text_field :end_latitude %> <br>

    <label for="start_longitude"> Start Longitude: </label>
    <%= p.text_field :start_longitude %> <br>

    <label for="end_longitude"> End Longitude: </label>
    <%= p.text_field :end_longitude %> <br>

    <label for="move_by"> Move By: </label>
    <%= p.datetime_field :move_by %> <br>

    <label for="remind_at"> Remind At: </label>
    <%= p.datetime_field :remind_at %> <br>
    
    <%= p.hidden_field :user_id, :value=>current_user.id %>

    <label for="car"> Car: </label>
    <%= p.select :car_id, Car.all.map{|x| [x.nickname, x.id]} %>
    <%= p.submit %>
<% end %>

app/views/parkings/show.html.erb
<h1> <%= @parkedCar.nickname %> </h1>
<h3> Current Status: </h3>
<h3> Intersection: </h3>
<h3> Move By: </h3>
<h3> Remind At: </h3>

app/views/parkings/update.html.erb
<%= form_for @parking do |p| %>
    <label for="active"> Active? </label>
    <%= p.check_box :active %> <br>

    <label for="address"> Address: </label>
    <%= p.text_field :address %> <br>

    <label for="start_latitude"> Start Latitude: </label>
    <%= p.text_field :start_latitude %> <br>

    <label for="end_latitude"> End Latitude: </label>
    <%= p.text_field :end_latitude %> <br>

    <label for="start_longitude"> Start Longitude: </label>
    <%= p.text_field :start_longitude %> <br>

    <label for="end_longitude"> End Longitude: </label>
    <%= p.text_field :end_longitude %> <br>

    <label for="move_by"> Move By: </label>
    <%= p.datetime_field :move_by %> <br>

    <label for="remind_at"> Remind At: </label>
    <%= p.datetime_field :remind_at %> <br>

    <label for="remind_at"> Remind At: </label>
    <%= p.datetime_field :remind_at %> <br>

    <%= p.hidden_field :user_id, :value=>current_user.id %>
    <label for="car"> Car: </label>
    <%= p.select :car_id, Car.all.map{|x| [x.nickname, x.id]} %>
    <%= p.submit %>
<% end %>

app/views/users/edit.html.erb
<% if user_signed_in? %>
    <%= link_to 'Home', root_path %>

    <h1> Edit Profile</h1>

    <%= form_for @user do |f| %>
        
        <label for="firstName"> First Name:</label>
        <%= f.text_field :first_name %>

        <label for="lastName"> Last Name:</label>
        <%= f.text_field :last_name %>

        <label for="phone"> Phone:</label>
        <%= f.text_field :phone %>

        <label for="email"> Email:</label>
        <%= f.text_field :email %>

        <label for="password"> Password:</label>
        <%= f.text_field :password %>

        <%= f.button :submit %>

    <% end %>

<% end %>

app/views/users/index.html.erb
<% if user_signed_in? %>
<div>
    <h1> Welcome back, <%= @user.first_name %>! </h1>

    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>

    <%= link_to 'Edit Profile', edit_user_path(@user) %>
    <%= link_to 'Delete Account', edit_user_path(@user) %>
</div>
<h2>
    <%= link_to 'Cars', cars_path %>
</h2>

<h2>
    <%= link_to 'Park', parkings_path %>
</h2>

<% end %>